# Site settings
title: DKG 2021
email: kontakt@dkg2021.de
description: Der 62. Deutsche Kongress für Geographie findet vom 29. September bis zum 2. Oktober 2021 in Frankfurt am Main statt. 
baseurl: "" 
url: "https://dkg2021.de"

twitter_username: dkg2021

# Build settings
markdown: kramdown
